-- local M = {}
-- M.setup = function ()
-- local view_status_ok, comment = pcall(require, "nvim_comment")
-- if not view_status_ok then
-- print('vim_comment not working')
-- return
-- end
-- comment.setup(
-- {
-- -- Linters prefer comment and line to have a space in between markers
-- marker_padding = true,
-- -- should comment out empty or whitespace only lines
-- comment_empty = true,
-- -- Should key mappings be created
-- create_mappings = true,
-- line_mapping = "<leader>cc",
-- operator_mapping = "<leader>c"
-- }
-- )
-- end
-- return M
